package net.huaat.system.pojo;

// Generated 2012-10-8 14:17:55 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import net.huaat.common.util.CustomDateSerializer;

import org.codehaus.jackson.map.annotate.JsonSerialize;

/**
 * TMenu generated by hbm2java
 */
@Entity
@Table(name = "t_menu")
public class TMenu implements java.io.Serializable {

	private String id;
	private String name;
	private String url;
	private String openType;
	private String parentId;
	private String isLeaf;
	private String menuType;
	private String des;
	private Date updateTime;
	private Integer orderRow;
	private String iconUrl;

	public TMenu() {
	}

	public TMenu(String id,String name, String url, String openType, String parentId,
			String isLeaf,String menuType,String des,Date updateTime,Integer orderRow,String iconUrl) {
		this.id = id;
		this.name = name;
		this.url = url;
		this.openType = openType;
		this.parentId = parentId;
		this.isLeaf = isLeaf;
		this.menuType=menuType;
		this.des = des;
		this.updateTime = updateTime;
		this.orderRow=orderRow;
		this.iconUrl=iconUrl;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "open_type", length = 10)
	public String getOpenType() {
		return this.openType;
	}

	public void setOpenType(String openType) {
		this.openType = openType;
	}

	@Column(name = "parent_id")
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "is_leaf", length = 10)
	public String getIsLeaf() {
		return this.isLeaf;
	}

	public void setIsLeaf(String isLeaf) {
		this.isLeaf = isLeaf;
	}

	@Column(name = "menu_type", length = 10)
	public String getMenuType() {
		return this.menuType;
	}

	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}
	
	@Column(name = "des", length = 200)
	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

	@Column(name = "order_row", length = 10)
	public Integer getOrderRow() {
		return this.orderRow;
	}

	public void setOrderRow(Integer orderRow) {
		this.orderRow = orderRow;
	}
	
	//@Temporal(TemporalType.TIMESTAMP)
	@JsonSerialize(using=CustomDateSerializer.class)
	@Column(name = "update_time", length = 0)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	
	@Column(name = "iconurl", length = 200)
	public String getIconUrl() {
		return this.iconUrl;
	}

	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl;
	}
	
}
